// <auto-generated />
namespace HospitalMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_doctor_hospital_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_doctor_hospital_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202405200958481_added_doctor_hospital_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
